sudo: required
dist: xenial
services:
  - xvfb
language: python
python: 3.8
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
addons:
  chrome: stable
before_script:
before_install:
  - wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - echo $PWD
script: 
  python test.py
